### ISSUE TITLE
USER STORY: Browse Memories

### ISSUE THREAD

**Issue by justynath** [justynath/remember-me#4]
As a **user** I want to **browse through shared memories** so I can **read others’ experiences and reflections**

**Success Criteria**:
  - A "Memories" page displays a list of user-submitted memories with titles content previews and media
  - Memories are sorted by most recent by default
  - Clicking on a memory opens a detailed view of that post

**Tasks**:
  - [x] Design and implement the "Memories" page layout
  - [x] Display previews of each memory with media and titles
  - [x] Implement sorting by most recent memories
  - [x] Test navigation and display of individual memories
